ALTER TABLE projects ADD COLUMN background TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN phase TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN target_users TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN core_problem TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN success_metrics TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN constraints TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN owner TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN roles TEXT NOT NULL DEFAULT '';
