import { useEffect, useState } from "react"
import { GaugeIcon } from "lucide-react"
import { toast } from "sonner"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { listAnalysisDatasets, createMetricDefinition, listMetricDefinitions, type AnalysisDatasetRecord, type MetricDefinitionRecord } from "@/services/product-document-service"

export function ProjectMetricPanel({ projectId, desktopRuntime, readOnly }: { projectId: string; desktopRuntime: boolean; readOnly: boolean }) {
  const [datasets, setDatasets] = useState<AnalysisDatasetRecord[]>([]); const [metrics, setMetrics] = useState<MetricDefinitionRecord[]>([]); const [id, setId] = useState(""); const [name, setName] = useState(""); const [datasetId, setDatasetId] = useState(""); const [operator, setOperator] = useState("mean"); const [field, setField] = useState(""); const [unit, setUnit] = useState("")
  async function refresh() { if (!desktopRuntime) return; try { const [nextDatasets, nextMetrics] = await Promise.all([listAnalysisDatasets(true, projectId), listMetricDefinitions(true, projectId)]); setDatasets(nextDatasets); setMetrics(nextMetrics); if (!datasetId) setDatasetId(nextDatasets[0]?.id ?? "") } catch (error) { toast.error(error instanceof Error ? error.message : "无法读取指标目录") } }
  useEffect(() => { void refresh() }, [projectId, desktopRuntime])
  async function save() { try { if (!id.trim() || !name.trim() || !datasetId || !field.trim()) throw new Error("请填写指标 ID、名称、数据集和字段"); const formula = operator === "conversion" ? { operator, numeratorField: field.split(",")[0]?.trim(), denominatorField: field.split(",")[1]?.trim() } : { operator, field: field.trim() }; await createMetricDefinition(desktopRuntime, { id: id.trim(), projectId, name: name.trim(), description: "", unit, formulaJson: JSON.stringify(formula), sourceDatasetId: datasetId }); await refresh(); toast.success("指标版本已保存") } catch (error) { toast.error(error instanceof Error ? error.message : "保存指标失败") } }
  return <Card><CardHeader><CardTitle><GaugeIcon className="mr-2 inline size-4" />指标字典</CardTitle><CardDescription>指标公式只能使用白名单算子；保存同一 ID 会递增版本，不覆盖历史定义。</CardDescription></CardHeader><CardContent className="flex flex-col gap-3"><div className="grid gap-2 sm:grid-cols-2"><Input value={id} onChange={(event) => setId(event.target.value)} placeholder="指标 ID" disabled={readOnly} /><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="指标名称" disabled={readOnly} /><select value={datasetId} onChange={(event) => setDatasetId(event.target.value)} className="h-9 rounded-md border bg-background px-2 text-sm" aria-label="指标数据集" disabled={readOnly}><option value="">选择数据集</option>{datasets.map((dataset) => <option key={dataset.id} value={dataset.id}>{dataset.title}</option>)}</select><select value={operator} onChange={(event) => setOperator(event.target.value)} className="h-9 rounded-md border bg-background px-2 text-sm" aria-label="指标公式" disabled={readOnly}><option value="count">count</option><option value="sum">sum</option><option value="mean">mean</option><option value="conversion">conversion</option></select></div><div className="flex gap-2"><Input value={field} onChange={(event) => setField(event.target.value)} placeholder={operator === "conversion" ? "成功字段,分母字段" : "字段名"} disabled={readOnly} /><Input value={unit} onChange={(event) => setUnit(event.target.value)} placeholder="单位" disabled={readOnly} /><Button type="button" onClick={() => void save()} disabled={readOnly || !desktopRuntime}>保存版本</Button></div>{metrics.length ? <div className="flex flex-wrap gap-2">{metrics.map((metric) => <Badge key={`${metric.id}:${metric.versionNumber}`} variant="outline">{metric.name} v{metric.versionNumber}</Badge>)}</div> : <p className="text-xs text-muted-foreground">暂无指标定义。</p>}</CardContent></Card>
}
