import { useEffect, useState } from "react"
import { SearchCheck } from "lucide-react"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { validateResearchEntryDraft, type ResearchType } from "@/domain/research-entry"
import { createResearchEntry, listResearchEntries, type ResearchEntryRecord } from "@/services/research-entry-service"
import { listResearchPlans, type ResearchPlanRecord } from "@/services/research-plan-service"
const empty = { planId: "", researchType: "interview" as ResearchType, title: "", sourceRef: "", accessedAt: "", insight: "", personaSuggestion: "" }
const labels: Record<string, string> = { interview: "访谈", survey: "问卷", desk: "案头研究", observation: "观察" }
export function ProjectResearchPanel({ projectId, desktopRuntime, readOnly }: { projectId: string; desktopRuntime: boolean; readOnly: boolean }) {
  const [form, setForm] = useState(empty); const [entries, setEntries] = useState<ResearchEntryRecord[]>([]); const [plans, setPlans] = useState<ResearchPlanRecord[]>([])
  useEffect(() => { if (!desktopRuntime) return; void Promise.all([listResearchEntries(true, projectId), listResearchPlans(true, projectId)]).then(([loadedEntries, loadedPlans]) => { setEntries(loadedEntries); setPlans(loadedPlans) }).catch((error) => toast.error(error instanceof Error ? error.message : "无法读取研究记录")) }, [desktopRuntime, projectId])
  async function save() { try { const draft = validateResearchEntryDraft(form); const saved = await createResearchEntry(true, { ...draft, planId: form.planId || undefined, id: crypto.randomUUID(), projectId }); setEntries((current) => [saved, ...current]); setForm(empty); toast.success("研究记录已保存") } catch (error) { toast.error(error instanceof Error ? error.message : "研究记录保存失败") } }
  return <Card><CardHeader><CardTitle><SearchCheck className="mr-2 inline size-4" />用户研究 / 外部研究</CardTitle><CardDescription>无搜索服务时仍可手动导入；每条洞察保留来源引用和访问日期，不自动把研究结论写成正式需求。</CardDescription></CardHeader><CardContent className="flex flex-col gap-3"><div className="grid gap-2 sm:grid-cols-2"><Input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="研究标题" disabled={readOnly} /><Input value={form.sourceRef} onChange={(e) => setForm({ ...form, sourceRef: e.target.value })} placeholder="来源链接或文件引用" disabled={readOnly} /><Input type="date" value={form.accessedAt} onChange={(e) => setForm({ ...form, accessedAt: e.target.value })} aria-label="访问日期" disabled={readOnly} /><select className="rounded-md border bg-background px-3 text-sm" value={form.researchType} onChange={(e) => setForm({ ...form, researchType: e.target.value as ResearchType })} aria-label="研究类型" disabled={readOnly}><option value="interview">访谈</option><option value="survey">问卷</option><option value="desk">案头研究</option><option value="observation">观察</option></select><select className="rounded-md border bg-background px-3 text-sm" value={form.planId} onChange={(e) => setForm({ ...form, planId: e.target.value })} aria-label="关联研究计划" disabled={readOnly}><option value="">不绑定研究计划</option>{plans.filter((plan) => plan.status !== "cancelled").map((plan) => <option key={plan.id} value={plan.id}>{plan.title}</option>)}</select></div><Textarea value={form.insight} onChange={(e) => setForm({ ...form, insight: e.target.value })} placeholder="研究洞察与证据摘要" disabled={readOnly} /><Textarea value={form.personaSuggestion} onChange={(e) => setForm({ ...form, personaSuggestion: e.target.value })} placeholder="画像/用户建议（可选）" disabled={readOnly} /><div className="flex justify-end"><Button onClick={() => void save()} disabled={readOnly || !desktopRuntime}>保存研究记录</Button></div>{entries.map((item) => <div key={item.id} className="rounded-md border p-3 text-sm"><div className="flex flex-wrap items-center gap-2"><p className="flex-1 font-medium">{item.title}</p><Badge variant="outline">{labels[item.researchType]}</Badge><Badge variant="outline">访问 {item.accessedAt}</Badge>{item.planId ? <Badge variant="outline">已绑定计划</Badge> : null}</div><p className="mt-1 text-muted-foreground">来源：{item.sourceRef}</p><p className="mt-1">{item.insight}</p>{item.personaSuggestion ? <p className="mt-1 text-muted-foreground">画像建议：{item.personaSuggestion}</p> : null}</div>)}</CardContent></Card>
}
