import { DatabaseSync } from "node:sqlite"
import { readdirSync, readFileSync } from "node:fs"

const db = new DatabaseSync(":memory:")
db.exec("PRAGMA foreign_keys = ON")
const migrations = readdirSync("src-tauri/migrations").filter((file) => file.endsWith(".sql")).sort()
for (const migration of migrations) db.exec(readFileSync(`src-tauri/migrations/${migration}`, "utf8"))

const now = "2026-07-16T12:00:00.000Z"
db.exec("BEGIN")
try {
  db.prepare("INSERT INTO projects (id, name, goal, status, start_date, end_date, progress, created_at, updated_at) VALUES (?, ?, ?, 'active', ?, ?, 0, ?, ?)").run("p8-example", "P8 示例项目", "验证完整产品经理闭环", "2026-07-01", "2026-09-30", now, now)
  db.prepare("INSERT INTO research_plans (id, project_id, title, objective, target_persona, questions_json, status, start_date, end_date, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, 'active', ?, ?, ?, ?)").run("plan-1", "p8-example", "访谈计划", "验证任务优先级痛点", "产品经理", '["每天如何安排待办？"]', "2026-07-10", "2026-07-20", now, now)
  db.prepare("INSERT INTO research_entries (id, project_id, plan_id, research_type, title, source_ref, accessed_at, insight, persona_suggestion, created_at, updated_at) VALUES (?, ?, ?, 'interview', ?, ?, ?, ?, ?, ?, ?)").run("entry-1", "p8-example", "plan-1", "用户访谈 1", "interview://participant-1", "2026-07-16", "跨模块待办难以统一判断", "高频项目负责人", now, now)
  db.prepare("INSERT INTO research_insights (id, project_id, plan_id, entry_id, title, statement, evidence_json, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, 'accepted', ?, ?)").run("insight-1", "p8-example", "plan-1", "entry-1", "统一驾驶舱", "用户需要跨模块确定性待办", '["interview://participant-1"]', now, now)
  db.prepare("INSERT INTO research_requirement_candidates (id, project_id, insight_id, title, description, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, 'accepted', ?, ?)").run("candidate-1", "p8-example", "insight-1", "统一驾驶舱", "聚合风险、依赖、决策和发布", now, now)
  db.prepare("INSERT INTO meetings (id, project_id, title, meeting_date, status, created_at, updated_at) VALUES (?, ?, ?, ?, 'parsed', ?, ?)").run("meeting-1", "p8-example", "研究需求确认会", "2026-07-16", now, now)
  db.prepare("INSERT INTO requirement_cards (id, meeting_id, project_id, current_version_id, title, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, 'draft', ?, ?)").run("requirement-1", "meeting-1", "p8-example", "requirement-version-1", "统一驾驶舱", now, now)
  db.prepare("INSERT INTO requirement_versions (id, requirement_card_id, version_number, title, content_json, evidence_json, source, is_confirmed, created_at) VALUES (?, ?, 1, ?, ?, ?, 'user', 0, ?)").run("requirement-version-1", "requirement-1", "统一驾驶舱", '{"description":"聚合风险、依赖、决策和发布","targetUsers":"","scenario":"","painPoint":"","acceptanceCriteria":[]}', '[{"paragraphId":"research:entry-1","sourceType":"research_entry","sourceId":"entry-1","quote":"聚合风险、依赖、决策和发布","startOffset":0,"endOffset":14}]', now)
  db.prepare("UPDATE research_requirement_candidates SET requirement_card_id = ?, updated_at = ? WHERE id = ? AND status = 'accepted' AND requirement_card_id IS NULL").run("requirement-1", now, "candidate-1")
  db.prepare("INSERT INTO project_risks (id, project_id, title, description, severity, probability, status, owner, due_date, mitigation, created_at, updated_at) VALUES (?, ?, ?, ?, 'high', 'possible', 'open', ?, ?, ?, ?, ?)").run("risk-1", "p8-example", "发布延期", "关键依赖未完成", "PM", "2026-07-18", "准备降级范围", now, now)
  db.prepare("INSERT INTO project_dependencies (id, project_id, title, description, dependency_type, owner, due_date, status, resolution, created_at, updated_at) VALUES (?, ?, ?, ?, 'approval', ?, ?, 'blocked', ?, ?, ?)").run("dep-1", "p8-example", "法务审批", "隐私条款待确认", "Legal", "2026-07-17", "提供最小数据方案", now, now)
  db.prepare("INSERT INTO releases (id, project_id, title, scope_json, checklist_json, rollback_plan, result, retrospective, follow_up_json, status, target_date, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, '', '', ?, 'ready', ?, ?, ?)").run("release-1", "p8-example", "v1 内测", '["今日驾驶舱"]', '["备份数据库","执行回归"]', "恢复上一安装包", '["复查采用率"]', "2026-07-20", now, now)
  db.prepare("INSERT INTO agent_runs (id, run_type, provider_mode, model, status, created_at, completed_at, agent_definition_id, project_id, trace_version, idempotency_key, metadata_json) VALUES (?, 'plan_engineer', 'local', 'eval', 'succeeded', ?, ?, 'plan-engineer:v2', ?, 1, ?, '{}')").run("plan-run-1", now, now, "p8-example", "plan-engineer:v2:p8-example:1")
  db.prepare("INSERT INTO agent_tool_proposals (id, project_id, target_type, target_id, agent_run_id, agent_definition_id, tool_key, expected_target_updated_at, payload_json, evidence_json, rationale, status, created_at, updated_at) VALUES (?, ?, 'research_plan', ?, ?, 'plan-engineer:v2', 'update_research_plan', ?, ?, ?, ?, 'pending_confirmation', ?, ?)").run("proposal-1", "p8-example", "plan-1", "plan-run-1", now, '{"objective":"验证优先级判断与中断场景"}', '[{"sourceType":"plan","sourceId":"plan-1","field":"objective","quote":"验证任务优先级痛点"}]', "补齐中断场景", now, now)
  const executedAt = "2026-07-16T12:01:00.000Z"
  const executedUpdate = db.prepare("UPDATE research_plans SET objective = ?, updated_at = ? WHERE id = ? AND project_id = ? AND updated_at = ?").run("验证优先级判断与中断场景", executedAt, "plan-1", "p8-example", now)
  if (executedUpdate.changes !== 1) throw new Error("deterministic proposal execution did not update exactly one target")
  db.prepare("UPDATE agent_tool_proposals SET status = 'executed', reviewed_at = ?, executed_at = ?, updated_at = ? WHERE id = ? AND status = 'pending_confirmation'").run(executedAt, executedAt, executedAt, "proposal-1")
  db.prepare("INSERT INTO agent_runs (id, run_type, provider_mode, model, status, created_at, completed_at, agent_definition_id, project_id, trace_version, idempotency_key, metadata_json) VALUES (?, 'plan_engineer', 'local', 'eval', 'succeeded', ?, ?, 'plan-engineer:v2', ?, 1, ?, '{}')").run("plan-run-2", executedAt, executedAt, "p8-example", "plan-engineer:v2:p8-example:2")
  db.prepare("INSERT INTO agent_tool_proposals (id, project_id, target_type, target_id, agent_run_id, agent_definition_id, tool_key, expected_target_updated_at, payload_json, evidence_json, rationale, status, created_at, updated_at) VALUES (?, ?, 'research_plan', ?, ?, 'plan-engineer:v2', 'update_research_plan', ?, ?, ?, ?, 'pending_confirmation', ?, ?)").run("proposal-2", "p8-example", "plan-1", "plan-run-2", executedAt, '{"targetPersona":"负责人"}', '[{"sourceType":"plan","sourceId":"plan-1","field":"targetPersona","quote":"产品经理"}]', "调整画像", executedAt, executedAt)
  const concurrentAt = "2026-07-16T12:02:00.000Z"
  db.prepare("UPDATE research_plans SET target_persona = ?, updated_at = ? WHERE id = ?").run("高级产品经理", concurrentAt, "plan-1")
  const staleUpdate = db.prepare("UPDATE research_plans SET target_persona = ?, updated_at = ? WHERE id = ? AND project_id = ? AND updated_at = ?").run("负责人", "2026-07-16T12:03:00.000Z", "plan-1", "p8-example", executedAt)
  if (staleUpdate.changes !== 0) throw new Error("stale proposal overwrote a concurrent plan update")
  db.prepare("UPDATE agent_tool_proposals SET status = 'stale', reviewed_at = ?, updated_at = ? WHERE id = ? AND status = 'pending_confirmation'").run(concurrentAt, concurrentAt, "proposal-2")
  db.prepare("INSERT INTO agent_runs (id, run_type, provider_mode, model, status, created_at, completed_at, agent_definition_id, project_id, trace_version, idempotency_key, metadata_json) VALUES (?, 'risk_review', 'local', 'eval', 'succeeded', ?, ?, 'risk-review:v2', ?, 1, ?, '{}')").run("risk-run-1", concurrentAt, concurrentAt, "p8-example", "risk-review:v2:p8-example:1")
  db.prepare("INSERT INTO agent_tool_proposals (id, project_id, target_type, target_id, agent_run_id, agent_definition_id, tool_key, expected_target_updated_at, payload_json, evidence_json, rationale, status, created_at, updated_at) VALUES (?, ?, 'project_risk', ?, ?, 'risk-review:v2', 'update_project_risk', ?, ?, ?, ?, 'pending_confirmation', ?, ?)").run("risk-proposal-1", "p8-example", "risk-1", "risk-run-1", now, '{"mitigation":"daily dependency review"}', '[{"field":"severity","quote":"high"}]', "reduce release exposure", concurrentAt, concurrentAt)
  const riskExecutedAt = "2026-07-16T12:04:00.000Z"
  const riskUpdate = db.prepare("UPDATE project_risks SET mitigation = ?, updated_at = ? WHERE id = ? AND project_id = ? AND updated_at = ? AND status != 'closed'").run("daily dependency review", riskExecutedAt, "risk-1", "p8-example", now)
  if (riskUpdate.changes !== 1) throw new Error("risk proposal execution did not update exactly one open target")
  db.prepare("UPDATE agent_tool_proposals SET status = 'executed', reviewed_at = ?, executed_at = ?, updated_at = ? WHERE id = ? AND status = 'pending_confirmation'").run(riskExecutedAt, riskExecutedAt, riskExecutedAt, "risk-proposal-1")
  db.prepare("INSERT INTO agent_runs (id, run_type, provider_mode, model, status, created_at, completed_at, agent_definition_id, project_id, trace_version, idempotency_key, metadata_json) VALUES (?, 'dependency_review', 'local', 'eval', 'succeeded', ?, ?, 'dependency-remediation:v1', ?, 1, ?, '{}')").run("dependency-run-1", riskExecutedAt, riskExecutedAt, "p8-example", "dependency-remediation:v1:p8-example:1")
  db.prepare("INSERT INTO agent_tool_proposals (id, project_id, target_type, target_id, agent_run_id, agent_definition_id, tool_key, expected_target_updated_at, payload_json, evidence_json, rationale, status, created_at, updated_at) VALUES (?, ?, 'project_dependency', ?, ?, 'dependency-remediation:v1', 'update_project_dependency', ?, ?, ?, ?, 'pending_confirmation', ?, ?)").run("dependency-proposal-1", "p8-example", "dep-1", "dependency-run-1", now, '{"owner":"Legal"}', '[{"field":"status","quote":"blocked"}]', "明确审批负责人", riskExecutedAt, riskExecutedAt)
  const dependencyExecutedAt = "2026-07-16T12:05:00.000Z"
  const dependencyUpdate = db.prepare("UPDATE project_dependencies SET owner = ?, updated_at = ? WHERE id = ? AND project_id = ? AND updated_at = ? AND status != 'resolved'").run("Legal", dependencyExecutedAt, "dep-1", "p8-example", now)
  if (dependencyUpdate.changes !== 1) throw new Error("dependency proposal execution did not update exactly one unresolved target")
  db.prepare("UPDATE agent_tool_proposals SET status = 'executed', reviewed_at = ?, executed_at = ?, updated_at = ? WHERE id = ? AND status = 'pending_confirmation'").run(dependencyExecutedAt, dependencyExecutedAt, dependencyExecutedAt, "dependency-proposal-1")
  db.prepare("INSERT INTO agent_runs (id,run_type,provider_mode,model,status,created_at,completed_at,agent_definition_id,project_id,trace_version,idempotency_key,metadata_json) VALUES(?,'release_preparation','local','eval','succeeded',?,?,'release-preparation:v1',?,1,?,'{}')").run("release-run-1",dependencyExecutedAt,dependencyExecutedAt,"p8-example","release-preparation:v1:p8-example:1")
  db.prepare("INSERT INTO agent_tool_proposals(id,project_id,target_type,target_id,agent_run_id,agent_definition_id,tool_key,expected_target_updated_at,payload_json,evidence_json,rationale,status,created_at,updated_at) VALUES(?,?,'release',?,?,'release-preparation:v1','update_release_preparation',?,?,?,?,'pending_confirmation',?,?)").run("release-proposal-1","p8-example","release-1","release-run-1",now,'{"rollbackPlan":"restore and verify"}','[{"field":"status","quote":"ready"}]',"strengthen rollback",dependencyExecutedAt,dependencyExecutedAt)
  const releaseExecutedAt="2026-07-16T12:06:00.000Z";const releaseUpdate=db.prepare("UPDATE releases SET rollback_plan=?,updated_at=? WHERE id=? AND project_id=? AND updated_at=? AND status IN ('planned','ready')").run("restore and verify",releaseExecutedAt,"release-1","p8-example",now);if(releaseUpdate.changes!==1)throw new Error("release proposal did not update one pre-release target");db.prepare("UPDATE agent_tool_proposals SET status='executed',reviewed_at=?,executed_at=?,updated_at=? WHERE id=?").run(releaseExecutedAt,releaseExecutedAt,releaseExecutedAt,"release-proposal-1")
  db.exec("COMMIT")
} catch (error) {
  db.exec("ROLLBACK")
  throw error
}

const counts = Object.fromEntries(["research_plans", "research_entries", "research_insights", "research_requirement_candidates", "project_risks", "project_dependencies", "releases"].map((table) => [table, db.prepare(`SELECT COUNT(*) AS count FROM ${table} WHERE project_id = ?`).get("p8-example").count]))
const foreignKeys = db.prepare("PRAGMA foreign_key_check").all()
const linkedRequirement = db.prepare("SELECT requirement_card_id FROM research_requirement_candidates WHERE id = ?").get("candidate-1").requirement_card_id
const reviewAgentDefinitions = db.prepare("SELECT COUNT(*) AS count FROM agent_definitions WHERE id IN ('research-insight:v1', 'risk-review:v1', 'release-review:v1', 'competitor-review:v1', 'research-plan-review:v1', 'knowledge-review:v1', 'plan-engineer:v1') AND permissions_json LIKE '%\"businessWriteAccess\":false%'").get().count
const planEngineerV2 = db.prepare("SELECT COUNT(*) AS count FROM agent_definitions WHERE id = 'plan-engineer:v2' AND output_schema_version = '2.0.0' AND permissions_json LIKE '%\"userConfirmationRequired\":true%'").get().count
const projectQaV2 = db.prepare("SELECT COUNT(*) AS count FROM agent_definitions WHERE id = 'project-qa:v2' AND input_schema_version = '2.0.0' AND permissions_json LIKE '%\"read_project_risks\"%' AND permissions_json LIKE '%\"businessWriteAccess\":false%'").get().count
const riskReviewV2 = db.prepare("SELECT COUNT(*) AS count FROM agent_definitions WHERE id = 'risk-review:v2' AND output_schema_version = '2.0.0' AND permissions_json LIKE '%\"userConfirmationRequired\":true%' AND permissions_json LIKE '%\"proposalOnly\":true%'").get().count
const dependencyRemediationV1 = db.prepare("SELECT COUNT(*) AS count FROM agent_definitions WHERE id = 'dependency-remediation:v1' AND output_schema_version = '1.0.0' AND permissions_json LIKE '%\"userConfirmationRequired\":true%' AND permissions_json LIKE '%\"proposalOnly\":true%'").get().count
const releasePreparationV1=db.prepare("SELECT COUNT(*) AS count FROM agent_definitions WHERE id='release-preparation:v1' AND permissions_json LIKE '%\"userConfirmationRequired\":true%'").get().count
const proposalFlow = Object.fromEntries(db.prepare("SELECT status, COUNT(*) AS count FROM agent_tool_proposals GROUP BY status").all().map((row) => [row.status, row.count]))
const finalPlan = db.prepare("SELECT objective, target_persona FROM research_plans WHERE id = ?").get("plan-1")
const finalRisk = db.prepare("SELECT mitigation, status FROM project_risks WHERE id = ?").get("risk-1")
const finalDependency = db.prepare("SELECT owner, status FROM project_dependencies WHERE id = ?").get("dep-1")
const finalRelease=db.prepare("SELECT rollback_plan,status FROM releases WHERE id=?").get("release-1")
const orchestrationSource = readFileSync("src/components/project-agent-orchestration-panel.tsx", "utf8")
const orchestrationRunnerSource = readFileSync("src/domain/agent-orchestration-runner.ts", "utf8")
const orchestrationMarkers = ["runAgentOrchestration", "abortRef", "signal: controller.signal", "research-plan-review:v1", "plan-engineer:v1", "knowledge-review:v1", "research-insight:v1", "risk-review:v1", "competitor-review:v1", "release-review:v1"]
const orchestrationRunnerMarkers = ["AbortSignal", 'status: "cancelled"', "options.signal?.aborted"]
const orchestrationReady = orchestrationMarkers.every((marker) => orchestrationSource.includes(marker)) && orchestrationRunnerMarkers.every((marker) => orchestrationRunnerSource.includes(marker))
if (Object.values(counts).some((count) => count !== 1) || linkedRequirement !== "requirement-1" || reviewAgentDefinitions !== 7 || planEngineerV2 !== 1 || projectQaV2 !== 1 || riskReviewV2 !== 1 || dependencyRemediationV1 !== 1 || releasePreparationV1 !== 1 || proposalFlow.executed !== 4 || proposalFlow.stale !== 1 || finalPlan.objective !== "验证优先级判断与中断场景" || finalPlan.target_persona !== "高级产品经理" || finalRisk.mitigation !== "daily dependency review" || finalRisk.status !== "open" || finalDependency.owner !== "Legal" || finalDependency.status !== "blocked" || finalRelease.rollback_plan!=="restore and verify" || finalRelease.status!=="ready" || foreignKeys.length || !orchestrationReady) throw new Error(`P8 flow invalid: ${JSON.stringify({ counts, linkedRequirement, reviewAgentDefinitions, planEngineerV2, projectQaV2, riskReviewV2, dependencyRemediationV1,releasePreparationV1, proposalFlow, finalPlan, finalRisk, finalDependency,finalRelease, foreignKeys, orchestrationReady })}`)
console.log(JSON.stringify({ migrations: migrations.length, project: "p8-example", counts, linkedRequirement, reviewAgentDefinitions, planEngineerV2, projectQaV2, riskReviewV2, dependencyRemediationV1, proposalFlow, finalRisk, finalDependency, staleOverwritePrevented: true, orchestrationReady, foreignKeyErrors: foreignKeys.length }, null, 2))
